### ISSUE TITLE
HA Test errors in python 3.7.6

### ISSUE THREAD

**Issue by ReneNulschDE** [ktnrg45/pyps4-homeassistant#32]
**External Application?**
Is the bug from use with another application? 
Name of Application: 'HA 0.140.0 DEV'

**Describe the bug**
HA PS4 integration tests are failing on with Python 3.7.6

```
ERROR    homeassistant.setup:setup.py:180 Error during setup of component ps4
Traceback (most recent call last):
  File "/home/rene/home-assistant/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/home/rene/home-assistant/homeassistant/components/ps4/__init__.py", line 56, in async_setup
    transport, protocol = await async_create_ddp_endpoint()
  File "/home/rene/home-assistant/.tox/py37/lib/python3.7/site-packages/pyps4_2ndscreen/ddp.py", line 130, in async_create_ddp_endpoint
    transport, protocol = await loop.create_task(connect)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1211, in create_datagram_endpoint
    raise ValueError("Passing `reuse_address=True` is no "
ValueError: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.
ERROR    homeassistant.core:core.py:139 Error doing job: Task exception was never retrieved
```

**To Reproduce**
1. Pull the latest code from HA
2. Setup a new venv with PY3.7.6
3. Start tests 

**Desktop (please complete the following information):**
 - OS: Linux MINT 19.1

**Additional context**
Looks like that this is due to a recent change in Python
[Issue 37228](https://bugs.python.org/issue37228)

**Comment by ktnrg45** [comment]
Thanks for the heads up! Fixed version should be in HA now.
